# 线上配置文件
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://114.132.63.84:3306/rmhapi
    username: user
    password: 123456
#server:
#  port: 7530
#  servlet:
#    context-path: /api